Long/create model and sqlalchemy for user
leth02/VL_Chat_App pull request #8
Opened 2021-12-14 00:01 UTC by khuolo01

- Create ORM for table users using SQLAlchemy.
- Create tests for the User model.
- Create simplified insert, delete, and select functions that interact with table users.
- The application will connect to the database through SQLAlchemy. However, the old connection using _sqlite3.connect()_ will be kept until everyone successfully changes to SQLAlchemy.

2021-12-17 05:43 UTC, leth02 requested changes
Please resolve these comments and make additional changes where necessary.

2021-12-17 05:43 UTC, leth02 commented on message_app/db/db.py
> +# of a database. In order to retrieve the same data, we need to use the same object.
Better comment
Create an SQLAlchemy instance that is used throughout the application. As we create a Flask instance dynamically by using factory pattern, we cannot pass it here (`DB = SQLAlchemy(app)`) because the app instance has not existed. Inside the factory function to create a Flask app instance, we need to call `get_db_SQLAlchemy `function which in turns will call `DB.init_app(current_app)` to initialize the use of the app with this database setup.
References: 
- https://flask-sqlalchemy.palletsprojects.com/en/2.x/contexts/
- https://flask-sqlalchemy.palletsprojects.com/en/2.x/api/#flask_sqlalchemy.SQLAlchemy.init_app

2021-12-17 05:43 UTC, leth02 commented on message_app/model.py
> +        return user
Please use decorators such as `@classmethod` or `@staticmethod`

2021-12-17 05:43 UTC, leth02 commented on message_app/model.py
> +    def __eq__(self, __o: User) -> bool:
Usse `other_user` instead of double underscores.

2021-12-17 05:43 UTC, leth02 commented on tests/conftest.py
> +from message_app.db.db import DB as _db
Do not use underscore for global object. This is not following convention.

2021-12-17 05:43 UTC, leth02 commented on tests/conftest.py
> +def db(app):
Should we have a longer and more detailed name for this function?

2021-12-17 05:43 UTC, leth02 commented on tests/conftest.py
>  def client(app):
We should give this function a more detailed name.

2021-12-17 05:43 UTC, leth02 commented on tests/conftest.py
> +    _db.app = app
This line has similar effect as `_db.init_app(app)`. Maybe using that instead for consistency purpose?

2021-12-17 21:56 UTC, vuongtranluc approved these changes

2021-12-21 03:04 UTC, leth02 approved these changes

2021-12-21 03:09 UTC, merged

2021-12-21 03:09 UTC, leth02 commented
LGTM